import Link from "next/link";
import { CompanyBrainMap, ResourceCard } from "../../src/components/ui";
import { pathways } from "../../src/data/siteContent";
import { conferences, internshipTimeline, semiconductorResources, semiconductorWork } from "../../src/data/researchResources";

export default function SemiconductorsPage() {
  return (
    <main>
      <section className="section pageIntro"><p className="kicker">One materials-science pathway</p><h1>Semiconductors Pathway Guide</h1><p>Use this guide to connect coursework and research with roles across fabrication, equipment, materials, devices, packaging, photonics, and data. Semiconductors are one pathway—not the only successful direction in Materials Science.</p></section>
      <section className="section sectionTight"><Link className="btn" href="/">← Back to Home</Link></section>

      <section className="section"><h2>What semiconductor work includes</h2><p>Each area below connects a part of the chip lifecycle to common industry roles and active research questions.</p><div className="workGrid">{semiconductorWork.map((area)=><article className="workCard" key={area.title}><h3>{area.title}</h3><p>{area.explanation}</p><div className="workDetail"><strong>Industry jobs</strong><span>{area.jobs}</span></div><div className="workDetail"><strong>Research topics</strong><span>{area.research}</span></div></article>)}</div></section>
      <section className="section"><h2>How UCF connects to this pathway</h2><div className="resourceGrid">{semiconductorResources.map((r)=><ResourceCard key={r.title} title={r.title} category={r.group} description={r.description} href={r.url} />)}</div></section>
      <section className="section"><div className="sectionHeading"><div><p className="kicker">Interactive industry map</p><h2>How semiconductor companies fit together</h2></div><span className="countPill">Select a branch</span></div><p>Explore the major employers in this repository by business model. Some companies operate across more than one category; they are placed under the branch most useful for understanding their primary role.</p><CompanyBrainMap /></section>
      <section className="section"><h2>Internship planning timeline</h2><p className="sourceNote">This is a planning pattern, not a guaranteed company deadline. Semiconductor roles open and close individually.</p><div className="timelineGrid">{internshipTimeline.map(([period,action])=><article className="stepCard" key={period}><p className="stepLabel">{period}</p><p>{action}</p></article>)}</div></section>
      <section className="section"><p className="kicker">A personal perspective</p><h2>What I learned in Dr. Banerjee's lab</h2><p>When I began studying Materials Science, I was interested in chemistry, mathematics, and physics, but I did not yet understand how those subjects came together as an engineering discipline. During my first meeting with Dr. Banerjee, he emphasized the relationship between a material's structure, how it is processed, and the properties it ultimately exhibits. Working in his lab turned that idea from something I learned in class into something I could observe and control through experiments.</p><p>Atomic layer deposition and atomic layer etching taught me that changing only a few atomic layers can completely transform how a material behaves. One moment that stayed with me was measuring a nanometer-thin conductive film on silicon. The coated and uncoated samples looked identical, but the coated surface measured only a few ohms while the uncoated surface behaved like an insulator at approximately 10<sup>15</sup> ohms. That contrast showed me how an almost invisible change in composition and processing can alter a material's electrical properties by many orders of magnitude.</p><p>The lab also helped me understand how broad Materials Science really is. The same atomic-scale processing ideas can contribute to transistors, solar cells, fuel cells, catalysts, and other technologies. Learning to connect surface chemistry, thin-film growth, characterization, electrical behavior, and device performance gave me a stronger understanding of the field as a whole—not simply one deposition technique.</p><p>At the same time, these experiences helped me find my own direction. I discovered that I especially enjoy creating materials, designing and improving processes, working in laboratory and cleanroom environments, and investigating why small processing changes produce different results. That led to my growing interest in semiconductor process engineering, thin films, nanomanufacturing, and eventually data-driven process optimization. Research did not require me to have my career figured out before I started; it gave me the experiences I needed to discover what genuinely interested me.</p><div className="startBox"><strong>My biggest takeaway:</strong> start by learning one process, one material system, or one measurement method. Following the questions that emerge from that experience can help you understand Materials Science more deeply and find the part of the field that excites you.</div></section>
      <section className="section"><h2>Conferences and networking</h2><p>Use technical meetings to learn what companies work on, practice technical conversations, meet hiring engineers, and follow up with context.</p><div className="resourceGrid">{conferences.map(c=><article className="resourceCard" key={c.name}><h3>{c.name}</h3><p>{c.focus}</p><a className="textLink" href={c.url} target="_blank" rel="noreferrer">Visit conference ↗</a></article>)}</div></section>
      <section className="section"><h2>Other Materials pathways</h2><div className="listCol">{pathways.map((p)=><article key={p.title} className="resourceCard"><h3>{p.title}</h3><p>{p.description}</p></article>)}</div></section>
      
      <section className="section"><Link className="btn" href="/faculty">What to do next: browse faculty</Link></section>
    </main>
  );
}
