"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { faculty } from "../data/siteContent";

export function Accordion({ title, children }: { title: string; children: React.ReactNode }) { return <details className="accordion"><summary>{title}</summary><div className="accordionBody">{children}</div></details>; }
export function DecisionCard({ title, description, href }: { title: string; description: string; href: string }) { return <article className="decisionCard"><h3>{title}</h3><p>{description}</p><Link className="btn" href={href}>Open</Link></article>; }
export function StepCard({ step, title, summary, nextAction, details }: { step: number; title: string; summary: string; nextAction: string; details: React.ReactNode }) { return <article className="stepCard"><p className="stepLabel">Step {step}</p><h3>{title}</h3><p>{summary}</p><p><strong>What to do next:</strong> {nextAction}</p><Accordion title="Learn more">{details}</Accordion></article>; }
export function ChecklistAccordion({ title, items, label = "Beginner awareness" }: { title: string; items: readonly string[]; label?: string }) { return <article className="stepCard"><p className="kicker">{label}</p><Accordion title={title}><ul>{items.map((x) => <li key={x}>{x}</li>)}</ul></Accordion></article>; }
export function MentorMeetingCard({ title, purpose, whenToUse, questions, deliverable }: { title: string; purpose: string; whenToUse: string; questions: readonly string[]; deliverable: readonly string[] }) { return <article className="stepCard"><h3>{title}</h3><p><strong>Purpose:</strong> {purpose}</p><p><strong>When to use:</strong> {whenToUse}</p><ul>{questions.slice(0,4).map((q)=><li key={q}>{q}</li>)}</ul><Accordion title="See more questions"><ul>{questions.slice(4).map((q)=><li key={q}>{q}</li>)}</ul></Accordion><p><strong>Deliverable/checklist</strong></p><ul>{deliverable.map((d)=><li key={d}>{d}</li>)}</ul></article>; }
export function PrincipleCard({ title, text }: { title: string; text: string }) { return <article className="resourceCard"><h3>{title}</h3><p>{text}</p></article>; }
export function ReadinessChecklist({ title, items }: { title: string; items: readonly string[] }) { return <ChecklistAccordion title={title} items={items} />; }
export function SemiconductorChecklist({ warning, sections }: { warning: string; sections: readonly { title: string; items: readonly string[] }[] }) { return <section className="section"><p className="startBox"><strong>Beginner awareness:</strong> {warning}</p><div className="listCol">{sections.map((s)=><ChecklistAccordion key={s.title} title={s.title} items={s.items} />)}</div></section>; }
export function TemplateBox({ title, content }: { title: string; content: string }) { const [copied,setCopied]=useState(false); return <article className="templateBox"><h3>{title}</h3><pre>{content}</pre><button className="btn" onClick={async()=>{await navigator.clipboard.writeText(content);setCopied(true);setTimeout(()=>setCopied(false),1200);}}>{copied?"Copied":"Copy"}</button></article>; }
export function ResourceCard({ title, category, description, href }: { title: string; category: string; description: string; href: string }) { return <article className="resourceCard"><p className="kicker">{category}</p><h3>{title}</h3><p>{description}</p><a href={href}>Open resource</a></article>; }
export function FacultyBrowser(){const [query,setQuery]=useState("");const [department,setDepartment]=useState("All");const [interest,setInterest]=useState("All");const departments=["All",...Array.from(new Set(faculty.map(f=>f.department)))];const interests=["All","Semiconductors","Computation","Quantum","Photonics","Reliability","Manufacturing"];const filtered=useMemo(()=>faculty.filter(f=>{const q=query.toLowerCase();return (!q||`${f.name} ${f.department} ${f.area}`.toLowerCase().includes(q))&&(department==="All"||f.department===department)&&(interest==="All"||f.area.toLowerCase().includes(interest.toLowerCase()));}),[query,department,interest]);return <section><div className="filterRow"><input placeholder="Search faculty or topic" value={query} onChange={(e)=>setQuery(e.target.value)} /><select value={department} onChange={(e)=>setDepartment(e.target.value)}>{departments.map(d=><option key={d}>{d}</option>)}</select><select value={interest} onChange={(e)=>setInterest(e.target.value)}>{interests.map(i=><option key={i}>{i}</option>)}</select></div><div className="listCol">{filtered.map(f=><article key={f.name} className="facultyCard"><h3>{f.name}</h3><p className="kicker">{f.department}</p><p>{f.area}</p><Accordion title="Expand"><p><strong>Student angle:</strong> {f.studentAngle}</p></Accordion></article>)}</div></section>}
