"use client";
import Link from "next/link";
import { useMemo, useState } from "react";
import { faculty } from "../data/siteContent";
import { companyGroups } from "../data/researchResources";

export function Accordion({ title, children }: { title: string; children: React.ReactNode }) { return <details className="accordion"><summary>{title}</summary><div className="accordionBody">{children}</div></details>; }
export function DecisionCard({ title, description, href }: { title: string; description: string; href: string }) { return <article className="decisionCard"><h3>{title}</h3><p>{description}</p><Link className="btn" href={href}>Open</Link></article>; }
export function StepCard({ step, title, summary, nextAction, details }: { step: number; title: string; summary: string; nextAction: string; details: React.ReactNode }) { return <article className="stepCard"><p className="stepLabel">Step {step}</p><h3>{title}</h3><p>{summary}</p><p><strong>What to do next:</strong> {nextAction}</p><Accordion title="Learn more">{details}</Accordion></article>; }
export function ChecklistAccordion({ title, items, label = "Beginner awareness" }: { title: string; items: readonly string[]; label?: string }) { return <article className="stepCard"><p className="kicker">{label}</p><Accordion title={title}><ul>{items.map((x) => <li key={x}>{x}</li>)}</ul></Accordion></article>; }
export function MentorMeetingCard({ title, purpose, whenToUse, questions, deliverable }: { title: string; purpose: string; whenToUse: string; questions: readonly string[]; deliverable: readonly string[] }) { return <article className="stepCard"><h3>{title}</h3><p><strong>Purpose:</strong> {purpose}</p><p><strong>When to use:</strong> {whenToUse}</p><ul>{questions.slice(0,4).map((q)=><li key={q}>{q}</li>)}</ul><Accordion title="See more questions"><ul>{questions.slice(4).map((q)=><li key={q}>{q}</li>)}</ul></Accordion><p><strong>Deliverable/checklist</strong></p><ul>{deliverable.map((d)=><li key={d}>{d}</li>)}</ul></article>; }
export function PrincipleCard({ title, text }: { title: string; text: string }) { return <article className="resourceCard"><h3>{title}</h3><p>{text}</p></article>; }
export function TemplateBox({ title, content }: { title: string; content: string }) { const [copied,setCopied]=useState(false); return <article className="templateBox"><h3>{title}</h3><pre>{content}</pre><button className="btn" onClick={async()=>{await navigator.clipboard.writeText(content);setCopied(true);setTimeout(()=>setCopied(false),1200);}}>{copied?"Copied":"Copy"}</button></article>; }
export function ResourceCard({ title, category, description, href }: { title: string; category: string; description: string; href: string }) { return <article className="resourceCard"><p className="kicker">{category}</p><h3>{title}</h3><p>{description}</p><a href={href}>Open resource</a></article>; }
export function FacultyBrowser(){const [query,setQuery]=useState("");const [interest,setInterest]=useState("All");const interests=["All","Semiconductor","Computation","Photonics","Biomaterials","Polymers","Energy","Metals","Manufacturing"];const filtered=useMemo(()=>faculty.filter(f=>{const text=`${f.name} ${f.title} ${f.area} ${f.studentAngle}`.toLowerCase();return (!query||text.includes(query.toLowerCase()))&&(interest==="All"||text.includes(interest.toLowerCase()));}),[query,interest]);return <section><div className="filterRow facultyFilters"><label><span>Search the directory</span><input placeholder="Name, material, technique, or application" value={query} onChange={(e)=>setQuery(e.target.value)} /></label><label><span>Research area</span><select value={interest} onChange={(e)=>setInterest(e.target.value)}>{interests.map(i=><option key={i}>{i}</option>)}</select></label><p className="resultCount">Showing {filtered.length} of {faculty.length} faculty</p></div><div className="facultyGrid">{filtered.map(f=><article key={f.name} className="facultyCard"><p className="kicker">{f.title}</p><h3>{f.name}</h3><p>{f.area}</p><Accordion title="Why a student might explore this group"><p>{f.studentAngle}</p><a href="https://mse.ucf.edu/facultystaff/" target="_blank" rel="noreferrer">Verify on the UCF directory ↗</a></Accordion></article>)}</div></section>}
export function CompanyBrainMap(){const [active,setActive]=useState<string>(companyGroups[0].id);const group=companyGroups.find(g=>g.id===active)!;return <div className="brainMap"><div className="brainMapCenter"><span>SEMICONDUCTOR</span><strong>INDUSTRY</strong></div><div className="brainBranches" role="tablist" aria-label="Semiconductor company types">{companyGroups.map((g,i)=><button key={g.id} role="tab" aria-selected={active===g.id} className={`brainBranch branch${i+1} ${active===g.id?"activeBranch":""}`} onClick={()=>setActive(g.id)}><span>{g.label}</span><small>{g.companies.length} companies</small></button>)}</div><section className="brainDetail" role="tabpanel"><p className="kicker">Selected industry branch</p><h3>{group.label}</h3><p>{group.description}</p><p><strong>Common roles:</strong> {group.roles}</p><div className="companyNodes">{group.companies.map(name=><span key={name}>{name}</span>)}</div></section></div>}
